id: I38A4D330
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:56:34+00:00'
last_modified: '2022-06-08T11:41:52.201738+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13795
  title: ཐེ་པནདིཏ་ཨནད་ཐེ་སིདདྷ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    D8CC:
      image_group_id: I1KG15382
      title: ''
      total_pages: 330
      order: 1
      base_file: D8CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
